# Generated by Django 3.0.3 on 2020-02-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phoneNumber',
            field=models.IntegerField(default='0', max_length=150),
        ),
    ]
