# Generated by Django 3.0.3 on 2020-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200204_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='degree',
            field=models.CharField(choices=[('Graduated', 'Graduated'), ('Freshman', 'Freshman'), ('Master Degree', 'Master Degree'), ('PHD', 'PHD')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='jobTitle',
            field=models.CharField(default='CEO', max_length=200, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zipCode',
            field=models.CharField(default='None', max_length=10, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phoneNumber',
            field=models.CharField(default='0', max_length=20, verbose_name='Phone Number'),
        ),
    ]
