# Generated by Django 3.0.3 on 2020-02-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200204_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='degree',
            field=models.CharField(blank=True, choices=[('Graduated', 'Graduated'), ('Freshman', 'Freshman'), ('Master Degree', 'Master Degree'), ('PHD', 'PHD')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='jobTitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zipCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code'),
        ),
    ]
